### ISSUE TITLE
Will this plugin work with Android Devices that don't support ARCore?

### ISSUE THREAD

**Issue by nixoletas** [juicycleff/flutter-unity-view-widget#1021]
Hello, thanks for the repo! I'm trying to thing a plugin that can work with non pro devices like my Xiaomi Redmi Note 12. I know that AR can work because there are some apps with AR that work on my android even without the ARCore. 

Thanks for the help!

**Comment by timbotimbo** [comment]
This plugin does not use or require ARCore. I've had it running on old Android 6 devices that don't support AR at all.

ARCore is simply something that you can use in the embedded Unity, just like in a regular Unity app.
In Unity it is your choice to make ARCore optional or required in the player settings.

##
Do note that the plugin on pub.dev is outdated and you will likely have to use the version from github in your pubspec.yaml file.

```yaml
flutter_unity_widget:
    git:
      url: https://github.com/juicycleff/flutter-unity-view-widget.git
      ref: master # branch name or commit hash
```
