### ISSUE TITLE
can't build because of pub get fail due to webview

### ISSUE THREAD

**Issue by kotran88** [juicycleff/flutter-unity-view-widget#803]
I'm using modelviewer-plus and hope to implement this also. 
but can't do this because of below error 

```

Because no versions of flutter_unity_widget match >2022.2.0 <2022.3.0-alpha1 and flutter_unity_widget 2022.2.0 depends on webview_flutter ^4.0.0, flutter_unity_widget >=2022.2.0 <2022.3.0-alpha1 requires webview_flutter ^4.0.0.
And because flutter_unity_widget >=2022.3.0-alpha1 depends on webviewx ^0.2.1, flutter_unity_widget >=2022.2.0 requires webview_flutter ^4.0.0 or webviewx ^0.2.1.
And because webviewx >=0.2.1 depends on webview_flutter ^2.0.13 and model_viewer_plus >=1.3.1 depends on webview_flutter ^3.0.4, model_viewer_plus >=1.3.1 is incompatible with flutter_unity_widget >=2022.2.0.
So, because flutter_unity_widget_example depends on both flutter_unity_widget ^2022.2.0 and model_viewer_plus ^1.5.0, version solving failed.
```
```

my pubspec.yaml

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_unity_widget: ^2022.2.0
  model_viewer_plus: ^1.5.0
  pointer_interceptor: ^0.9.3+2

```

I tried adding 

  webviewx : ^0.2.1
webview_flutter ^4.0.0

but same result.
