### ISSUE TITLE
Experimental Unity 6 (6000) support for Android.

### ISSUE THREAD

**Issue by timbotimbo** [juicycleff/flutter-unity-view-widget#967]
## Description
Unity 2023.1 and 6 (6000.0) include breaking changes for the Android version of this plugin.
And given that 2023.3 turned into 6000, I decided to implement support for Unity 6000.

For a litte more info, see the PR https://github.com/juicycleff/flutter-unity-view-widget/pull/966

## Installing & testing

This alpha version is now live in the [experimental/unity_6000](https://github.com/juicycleff/flutter-unity-view-widget/tree/experimental/unity_6000) branch.

You can either download it and include the plugin using a relative path
```
flutter_unity_widget:
    path: <folder path>
```
or include it using the git url
```
flutter_unity_widget:
    git:
      url: https://github.com/juicycleff/flutter-unity-view-widget.git
      ref: experimental/unity_6000 # branch name
```

## Setup
1. Your Flutter project will need to use Java 17 and gradle 8.x, 
Check the example project in the unity_6000 branch for the relevant build.gradle files.

2. After the Unity export, `android/unityLibrary/build.gradle` might include a broken import.  
   - Either fix this automatically by updating your `Assets/FlutterUnityIntegration/Editor/build.cs` file with the one from the example project. 
   - Or comment the 2nd line `apply from: '../shared/keepUnitySymbols.gradle'` in `unityLibrary/build.gradle`
