### ISSUE TITLE
Compiling error flutter 3.24

### ISSUE THREAD

**Issue by lorisgir** [juicycleff/flutter-unity-view-widget#973]
**Describe the bug**
After the update to flutter 3.24 every time I try to build & run on the emulator I get these error messages:
`e: file:///Users/lorisgir/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.1/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetPlugin.kt:97:9 Cannot weaken access privilege 'public' for 'lifecycle' in 'LifecycleOwner'
e: file:///Users/lorisgir/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.1/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetPlugin.kt:97:21 'lifecycle' hides member of supertype 'LifecycleOwner' and needs 'override' modifier`

I already tried to run flutter clean and rebuild the unity project from unity but always the same error

**Unity:**
 - OS: MacOS
 - Version 2022.3.36

**Smartphone:**
 - Device: Pixel 8 Emulator
 - OS: Android
 - Version 15

**Comment by viktorsht** [comment]
@timbotimbo Thank you very much! You helped me a lot! God bless you!

**Comment by artificerchris** [comment]
@timbotimbo Any chance you could apply that same fix over on the 6.0 branch? I'm testing it out and just hit this error, and one other one I'm about to write up.

**Comment by timbotimbo** [comment]
I added the fix to the `master` branch, to make sure it gets included in a future update.

@artificerchris 
I've merged the updated master into the 6000 branch as well.

**Comment by artificerchris** [comment]
Thank you very much!

**Comment by chetu-ko** [comment]
I am also getting the same error with version 3.19 version of Flutter.

```
flutter_unity_widget:
    git:
      url: https://github.com/juicycleff/flutter-unity-view-widget.git
      ref: flutter_3.24_android_hotfix # branch name
      # UPDATE: this fix is now included in the master branch
```
I am adding the above git URL and the branch has not fixed my issue. Still facing the same problem, with tagged issue #981
