### ISSUE TITLE
Execution failed for task ':flutter_unity_widget:compileDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

### ISSUE THREAD

**Issue by aryamanpathak2022** [juicycleff/flutter-unity-view-widget#987]
**Describe the bug**
While building the flutter project, I got this error which states two same JVM signature (getLifecycle()) exist 

**Screenshots**
![image](https://github.com/user-attachments/assets/2e3001cc-07d9-46b8-a735-fb276c3c60bc)

**Unity (please complete the following information):**
 - OS: Android
 - Version 2022.3

**Comment by timbotimbo** [comment]
Switching to Flutter 3.24 [introduces kotlin compilation errors](https://github.com/juicycleff/flutter-unity-view-widget/issues/973) related to `Lifecycle`. 
Although a different error message, I believe this is the same issue and you should try the fix from the link above.
Import an updated plugin by the git url:

`pubspec.yaml`
```
flutter_unity_widget:
    git:
      url: https://github.com/juicycleff/flutter-unity-view-widget.git
      ref: master # branch name 
```
